package org.sc.cbm.e193.praia.insercao.wizard.ui;

import android.app.Activity;
import android.content.Intent;
import android.database.DataSetObserver;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.melnykov.fab.FloatingActionButton;

import org.sc.cbm.e193.R;
import org.sc.cbm.e193.praia.DbAdapter.GVMsDbAdapter;
import org.sc.cbm.e193.praia.insercao.GVMListViewCursorAdaptorActivity;
import org.sc.cbm.e193.praia.insercao.wizard.model.GVMPage;
import org.sc.cbm.e193.praia.pojo.GVM;
import org.sc.cbm.e193.praia.pojo.GVMAdapter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

public class GVMFragment extends Fragment {
    private static final String ARG_KEY = "key";

    private PageFragmentCallbacks mCallbacks;
    private String mKey;
    private GVMPage mPage;
    private ArrayAdapter<GVM> mGVMAdapter;
    private ArrayList<GVM> mGVMList;
    private ListView mGVMView;
    private FloatingActionButton mFabView;
    private GVMsDbAdapter dbHelper;

    public GVMFragment() {
    }

    public static GVMFragment create(String key) {
        Bundle args = new Bundle();
        args.putString(ARG_KEY, key);

        GVMFragment fragment = new GVMFragment();
        fragment.setArguments(args);

        return fragment;

    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Bundle args = getArguments();
        mKey = args.getString(ARG_KEY);
        mPage = (GVMPage) mCallbacks.onGetPage(mKey);

        mGVMList = new ArrayList<GVM>();

        dbHelper = new GVMsDbAdapter(getActivity());
        dbHelper.open();
    }

    /*
     *   Beyond the common routines, does the refill job when user comes back to this fragment for
     *   review or correction of any data
     */
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_praia_insercao_wizard_page_gvm, container, false);
        ((TextView) rootView.findViewById(android.R.id.title)).setText(mPage.getTitle());

        mGVMAdapter = new GVMAdapter(getActivity(), mGVMList);
        mGVMView = (ListView) rootView.findViewById(R.id.list_gvm_added);
        mGVMView.setAdapter(mGVMAdapter);

        mFabView = (FloatingActionButton) rootView.findViewById(R.id.fab);
        mFabView.attachToListView(mGVMView);

        String sGVMList = mPage.getData().getString(GVMPage.GVM_LIST_DATA_KEY);
        if(sGVMList != null) {
            loadGVMList(sGVMList);
        }

        return rootView;
    }

    /**
     * Loads GVMList using string generated by getGVMListRegString
     *
     * @param sGVMList string generated by getGVMListRegString
     */
    private void loadGVMList(String sGVMList) {
        List<String> GVMsReg = Arrays.asList(sGVMList.split("\\s*,\\s*"));

        for (String reg : GVMsReg)
            mGVMList.add(dbHelper.fetchGVMByRegistration(reg));

        mGVMAdapter.notifyDataSetChanged();
    }

    @Override
    public void onAttach(Activity activity) {
        super.onAttach(activity);

        if (!(activity instanceof PageFragmentCallbacks)) {
            throw new ClassCastException("Activity must implement PageFragmentCallbacks");
        }

        mCallbacks = (PageFragmentCallbacks) activity;
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mCallbacks = null;
    }

    /*
     *   Adds informations to the final data's list while the user is filling the fields
     */
    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mFabView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(getActivity(), GVMListViewCursorAdaptorActivity.class);
                startActivityForResult(intent, 1);
            }
        });

        mGVMView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                mGVMList.remove(position);
                mGVMAdapter.notifyDataSetChanged();
            }
        });

        mGVMAdapter.registerDataSetObserver(new DataSetObserver() {
            @Override
            public void onChanged() {
                super.onChanged();
                Bundle bundle = mPage.getData();
                String gvmComaSeparated = getGVMListRegString();
                bundle.putString(GVMPage.GVM_LIST_DATA_KEY, gvmComaSeparated);
                mPage.notifyDataChanged();
            }
        });
    }

    /**
     * Get gvm's registrations string from list
     *
     * @return ex: "9334742, 9334741, 9334740", without quotes <br> if list is empty
     */
    private String getGVMListRegString() {
        String gvmListReg = new String();

        if (mGVMList.size() == 0) {
            gvmListReg = null;
        } else {
            for(int i = 0; i < mGVMList.size() - 1; i++) {
                gvmListReg = gvmListReg + mGVMList.get(i).getRegistration() + ", ";
            }
            gvmListReg = gvmListReg + mGVMList.get(mGVMList.size() - 1).getRegistration();

        }

        return gvmListReg;
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
                if (requestCode == 1) {
                    if(resultCode == getActivity().RESULT_OK){
                        GVM gvm = new GVM();
                        gvm.setName(data.getStringExtra(GVMsDbAdapter.KEY_NAME));
                        gvm.setRank(data.getStringExtra(GVMsDbAdapter.KEY_RANK));
                        gvm.setRegistration(data.getStringExtra(GVMsDbAdapter.KEY_REGISTRATION));

                        mGVMAdapter.add(gvm);
                    }
                }
    }

    @Override
    public void setMenuVisibility(boolean menuVisible) {
        super.setMenuVisibility(menuVisible);

        // In a future update to the support library, this should override setUserVisibleHint
        // instead of setMenuVisibility.
//        if (mNameView != null) {
//            InputMethodManager imm = (InputMethodManager) getActivity().getSystemService(
//                    Context.INPUT_METHOD_SERVICE);
//            if (!menuVisible) {
//                imm.hideSoftInputFromWindow(getView().getWindowToken(), 0);
//            }
//        }
    }
}
